config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments,        :only => [:create]
  resources :requests,        :only => [:destroy, :create]
  resources :services
  resources :posts,           :only => [:show], :path => '/p/'
  resources :people do
    resources :status_messages
    resources :photos
  end

  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match 'photos/make_profile_photo' => 'photos#make_profile_photo'
  resources :photos, :except => [:index]

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'getting_started_completed', :to => 'users#getting_started_completed'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',      :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',     :to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',            :to => 'aspects#manage'
  resources :aspects,                :except => [:edit]

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'

  #root
  root :to => 'home#show'
end

app/models/status_message.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class StatusMessage < Post
  include Diaspora::Socketable
  include YoutubeTitles
  require File.join(Rails.root, 'lib/youtube_titles')
  
  validates_length_of :message, :maximum => 1000, :message => "please make your status messages less than 1000 characters"
  xml_name :status_message
  xml_reader :message

  key :message, String
  many :photos, :class => Photo, :foreign_key => :status_message_id, :dependent => :destroy
  validate :message_or_photos_present?

  attr_accessible :message

  before_save do
    get_youtube_title message
  end
  def to_activity
        <<-XML
  <entry>
    <title>#{self.message}</title>
    <link rel="alternate" type="text/html" href="#{person.url}status_messages/#{self.id}"/>
    <id>#{person.url}status_messages/#{self.id}</id>
    <published>#{self.created_at.xmlschema}</published>
    <updated>#{self.updated_at.xmlschema}</updated>
    <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  </entry>
        XML
  end

  protected

  def message_or_photos_present?
    if self.message.blank? && self.photos.count == 0
      errors[:base] << 'Status message requires a message or at least one photo'
    end
  end

end

app/controllers/status_messages_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class StatusMessagesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => :show

  def create

    if params[:status_message][:aspect_ids] == "all"
      params[:status_message][:aspect_ids] = current_user.aspects.collect{|x| x.id}
    end

    photos = Photo.all(:id.in => [*params[:photos]], :diaspora_handle => current_user.person.diaspora_handle)

    public_flag = params[:status_message][:public]
    public_flag.to_s.match(/(true)/) ? public_flag = true : public_flag = false
    params[:status_message][:public] = public_flag 
    @status_message = current_user.build_post(:status_message, params[:status_message])


    if photos || @status_message.save!(:safe => true)
      raise 'MongoMapper failed to catch a failed save' unless @status_message.id

      @status_message.photos += photos unless photos.nil?
      current_user.add_to_streams(@status_message, params[:status_message][:aspect_ids])
      current_user.dispatch_post(@status_message, :to => params[:status_message][:aspect_ids], :url => post_url(@status_message))
      

      for photo in photos
        photo.public = public_flag
        photo.save
        current_user.add_to_streams(photo, params[:status_message][:aspect_ids])
        current_user.dispatch_post(photo, :to => params[:status_message][:aspect_ids])
      end

      respond_to do |format|
        format.js{ render :json => { :post_id => @status_message.id,
                                     :html => render_to_string(
                                       :partial => 'shared/stream_element', 
                                       :locals => {
                                         :post => @status_message, 
                                         :person => @status_message.person,
                                         :photos => @status_message.photos,
                                         :comments => [],
                                         :aspects => current_user.aspects, 
                                         :current_user => current_user
                                        }
                                     )
                                    },
                                     :status => 201 }
        format.html{ respond_with @status_message }
      end
    else
      respond_to do |format|
        format.js{ render :status => 406 }
      end
    end
  end

  def destroy
    @status_message = current_user.my_posts.where(:_id =>  params[:id]).first
    if @status_message
      @status_message.destroy
    else
      Rails.logger.info "event=post_destroy status=failure user=#{current_user.diaspora_handle} reason='User does not own post'"
    end

    respond_with :location => root_url
  end

  def show
    @status_message = current_user.find_visible_post_by_id params[:id]
    comments_hash = Comment.hash_from_post_ids [@status_message.id]
    person_hash = Person.from_post_comment_hash comments_hash
    @comment_hashes = comments_hash[@status_message.id].map do |comment|
      {:comment => comment,
        :person => person_hash[comment.person_id]
      }
    end
    respond_with @status_message
  end
end

app/helpers/status_messages_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module StatusMessagesHelper
  def my_latest_message
    unless @latest_status_message.nil?
      return @latest_status_message.message
    else
      return I18n.t('status_messages.helper.no_message_to_display')
    end
  end
end

app/views/status_messages/_new_status_message.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= form_for StatusMessage.new, :remote => true do |f|
  = f.error_messages
  %p
    = f.text_field :message, :value => t('.tell_me_something_good')
    = f.submit t('.oh_yeah'), :class => 'button'

app/views/status_messages/_status_message.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%p
  = markdownify(post.message, :youtube_maps => post[:youtube_titles])

- if photos.count > 0
  .photo_attachments
    - for photo in photos
      = link_to (image_tag photo.url(:thumb_medium)), photo_path(photo)

app/views/status_messages/show.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'shared/author_info', :person => @status_message.person, :post => @status_message

.span-14.append-1.last
  #show_text
    %p
      = markdownify(@status_message.message, :youtube_maps => @status_message[:youtube_titles])

    - for photo in @status_message.photos
      = link_to (image_tag photo.url(:thumb_small)), photo_path(photo)

  %p.time
    = how_long_ago(@status_message)

  %hr

  = link_to t('.permalink'), post_path(@status_message)
  %br
  - if current_user.owns? @status_message
    = link_to t('.destroy'), @status_message, :confirm => t('are_you_sure'), :method => :delete

.span-9.last
  %h4{:style=>"margin-bottom:5px;"}= t('_comments')
  %div{:class => 'stream show', :id => 'status_message_stream'}
    %li.message{:data=>{:guid=>@status_message.id}}
      = render "comments/comments", :post_id => @status_message.id, :comment_hashes => @comment_hashes